### ISSUE TITLE
Nombre max de messages

### ISSUE THREAD

**Issue by lmichel** [lmichel/vo-grimoire#20]
Du fait que l'utilisateur peut modifier à la main le nombre de messages retournés, il fait faire un controle et une limitation  à posteriori de ce paramètre avant envoie de la requête.
Question: Ce MAXR_ECORDS n'est il pas paramérable au niveau d'ES ?

**Comment by EnzOuille** [comment]
Modification ajoutée, elle est ajouté dans les settings à la création d'un index,max_result_windows
