### ISSUE TITLE
URL des threads num2

### ISSUE THREAD

**Issue by lmichel** [lmichel/vo-grimoire#9]
Lorsque je me connecte à
http://saada.unistra.fr/esmail/www/index.html?thread=registry_76

L'obtiens bien l'affichage du thread mais la nouvelle URL sur la boite modale est de la forme 
http://saada.unistra.fr/esmail/www/index.html?thread=registry_76&thread=registry_76

Duplication du parametre

**Comment by EnzOuille** [comment]
Correction ajoutée (à tester)
